### ISSUE TITLE
Obtain usage data for bare metal and generate initial invoice

### ISSUE THREAD

**Issue by QuanMPhm** [CCI-MOC/bare-metal-usage-scripts#1]
As part of nerc-project/operations#831, we want to have a way to pull usage for bare metal (BM), and turn them into invoices that we can process with `CCI-MOC/invoicing`, similar to `CCI-MOC/openshift-usage-scripts` and `CCI-MOC/openstack-billing-from-db`.

To do:
- [x] Determine storage locations for the BM invoices (likely S3?)

@joachimweyl @knikolla @naved001 Let me know if there are more things that need to be considered.

**Comment by knikolla** [comment]
> Determine storage locations for the BM invoices (likely S3?)

Yes, all Service Invoices should be in the `nerc-invoicing` B2 bucket under the key `/Invoices/<Invoice Month>/Service Invoices/<Service Name> <Invoice Month>.csv`

See first section of https://docs.google.com/document/d/1b5QmsMA4aNz-v-zPIcrnKkpNsDgu1WKU9Uq2BMpQn2g/edit

**Comment by tzumainn** [comment]
@joachimweyl what ESI commands do you run to generate your reports?  I'll need to update various OpenStack API policies for a reader account, and I just want to make sure the needed commands will work.

**Comment by joachimweyl** [comment]
`OpenStack esi lease list --status any --long`

**Comment by tzumainn** [comment]
It looks like there may be an issue in ESI that prevents custom policies from being applied. I can try and fix it; in the meantime, would it make sense to simply obtain a json output of the command from @joachimweyl to write a script against?

**Comment by joachimweyl** [comment]
@tzumainn sounds good, what is required to retrieve the json file?

**Comment by tzumainn** [comment]
Oh, just run the openstack command with `-f json` - it'll give you the exact same contents, simply formatted as json.

**Comment by joachimweyl** [comment]
json file provided to @QuanMPhm for inital testing

**Comment by QuanMPhm** [comment]
@larsks @knikolla As part of creating the initial POC, I was considering using `Pydantic` to validate the baremetal usage file obtained from ESI. Do you believe that would be nessecary?

I thought it be nice to ensure the usage data follows a certain syntax, and that we would get a warning if the usage data ever changes format in the future.

**Comment by larsks** [comment]
It is always a good idea to validate the data your receive, and pydantic is a good tool for the job. I think in most cases pydantic makes the data easier to work with, and it certainly makes it easier to filter the data for only the fields you care about.

**Comment by QuanMPhm** [comment]
@knikolla @naved001 While writing the test cases for the intial POC, I was wondering if there was a way to write the scripts such that it could dynamically find the list of available SUs are. Right now I'm hardcoding the list of valid SUs like our other billing scripts, but was wondering if we could remove the need for this "hardcoding". Doing so would remove to the need to edit the billing scripts once in a while when we come up with a new SU. 

Let me know what your thought are, and if it's worth pursuing in my POC

**Comment by larsks** [comment]
>  was wondering if there was a way to write the scripts such that it could dynamically find the list of available SUs are

I would vote for adding structure to the [`rates.yaml`](https://github.com/CCI-MOC/nerc-rates/blob/main/rates.yaml) file in [nerc-rates](https://github.com/CCI-MOC/nerc-rates). Right now it is effectively an enormous key/value file where the keys can be SUs, feature flags, credit definitions, etc. With no structure to the file it's impossible to use it without substantial external knowledge.

If you were to turn the comments that dive the file into parts into dictionary keys, so that instead of this:

```
#################################################
# Service Unit Rates
#################################################
- name: CPU SU Rate
  history:
    - value: "0.013"
      from: 2023-06

- name: GPUA100SXM4 SU Rate
  history:
    - value: "2.078"
      from: 2023-06
.
.
.
#################################################
# Feature Flags
#################################################
.
.
.
```

You have this:

```
service_unit_rates:
  - name: CPU SU Rate
    history:
      - value: "0.013"
        from: 2023-06

  - name: GPUA100SXM4 SU Rate
    history:
      - value: "2.078"
        from: 2023-06

feature_flags:
.
.
.
```

(etc.)


It would be much easier to do things like "give me a list of all the service units" or "give me a list of the feature flags".

**Comment by naved001** [comment]
> I was wondering if there was a way to write the scripts such that it could dynamically find the list of available SUs are. Right now I'm hardcoding the list of valid SUs like our other billing scripts, but was wondering if we could remove the need for this "hardcoding". Doing so would remove to the need to edit the billing scripts once in a while when we come up with a new SU.

In OpenShift, based on the model of GPU we determine the type of SU. The GPU model is value of the label (nvidia.com/gpu.product) applied by the nvidia GPU operator. We'll need to put this information in the SU definitions then. I imagine something similar for the openstack SUs. 

But this will only work for regular whole GPUs. Right now we don't offer MIG GPUs, but I had updated the openshift code to work with MIG GPUs, and for that we need to additionally need to know the resource type (`nvidia.com/gpu` for whole GPUs vs `nvidia.com/mig-1g.5gb` for a specific MIG config) so would that information be also added to the SU definition. It would certainly simplify the openshift invoicing code but we will need to add a bunch of more information in nerc-rates.

I am not saying we do this, but this is the information we'll need to have
```yaml
# for a non MIG SU on A100SXM4 on OpenShift
- name: GPU Model in OpenShift GPUA100SXM4 SU
  history:
    - value: "nvidia.com/A100_SMX4_40GB"
      from: 2023-06

- name: GPU Resource in OpenShift GPUA100SXM4 SU # or not because this can be the default unless we add AMD GPUs
  history:
    - value: "nvidia.com/gpu"
      from: 2023-06

# if we want to support MIG for billing
# for a MIG SU on A100SXM4 on OpenShift
- name: GPU Model in OpenShift GPUA100SXM4 SU
  history:
    - value: "nvidia.com/A100_SMX4_40GB"
      from: 2023-06

- name: GPU Resource in OpenShift GPUA100SXM4 MIG1 SU
  history:
    - value: "nvidia.com/mig-2g.10gb"
      from: 2023-06

```

I feel like we are really pushing the limits of what nerc-rates is meant to do lol
